#!/usr/bin/env bash
set -o pipefail

[[ -n "${TRACE}" ]] && set -x

readonly TMP_DIR="${TMP_DIR:-/tmp}"
readonly LINUX_OS="/etc/os-release"
readonly DEBIAN_OS="debian"
readonly DEFAULT_ACTIONS="remove install version"
readonly DT_FORMAT="+%Y-%m-%d %H:%M:%S"
declare PLATFORM

# Internal Function
error() {
  local NOW

  NOW=$(date "${DT_FORMAT}")
  echo "${NOW} ERROR: $*"
  exit 1
}

# Note warn() exists in some OS 
warning() {
  local NOW

  NOW=$(date "${DT_FORMAT}")
  echo "${NOW} WARN:  $*"
  return 0
}

# Internal Function
info() {
  local NOW

  NOW=$(date "${DT_FORMAT}")
  echo "${NOW} INFO:  $*"
  return 0
}

# Internal Function
completed() {
  info "Completed actions for '${PRODUCT}'"
  exit 0
}

##
## Provide the version of the product
##
version() {
  ${PRODUCT} --version
}

noop() {
  warning "'${1}' is not an operation for '${PRODUCT}'"
}

##
## Status of the product sevice
##
status() {
  noop "${FUNCNAME[0]}"
}

##
## Start the product sevice and check the status
##
start() {
  noop "${FUNCNAME[0]}"
}

##
## Stop the product sevice and check the status
##
stop() {
  noop "${FUNCNAME[0]}"
}

env-exists() {
  for ENV in "$@"; do
    [[ -z "${!ENV}" ]] && error "'${ENV}' must be configured"
  done
}
	
install-linux() {
  info "Installing '${PRODUCT}' on '${PLATFORM}'"
  
  [[ ! -f "${LINUX_OS}" ]] && error "Unable to detemrine '${PLATFORM}' OS. Missing '${LINUX_OS}'"
  OS=$(grep "^ID_LIKE" /etc/os-release | cut -d'=' -f2)
  [[ -z "${OS}" ]] && error "Unable to determine OS from '${LINUX_OS}'"

  case "${OS}" in
    "${DEBIAN_OS}")
        info "Checking..."
        info "Installing for '${OS}'"
	cd "${TMP_DIR}" || exit 1
	curl -s https://packagecloud.io/install/repositories/akopytov/${PRODUCT}/script.deb.sh | sudo bash
        sudo apt -y install "${PRODUCT}"
	RC="$?"
	[[ "${RC}" -ne 0 ]] && warn "installation returned '${RC}'"
      ;;
    *)
     error "'${OS}' is not yet supported"
     ;;
  esac
}

install() {
  PLATFORM="$(uname)"
  case "${PLATFORM}" in
    "Linux") 
      install-linux
      ;;
    *)
      error "'${PLATFORM}' is not yet supported for '${PRODUCT}'"
      ;;
  esac
}

remove() {
  stop
  sudo apt remove -y "${PRODUCT}"
}

purge() {
  stop
  remove
  sudo apt purge -y "${PRODUCT}"
}


initialization() {
  local INIT_CNF

  INIT_CNF="$(dirname "${BASH_SOURCE[0]}")/.product.cnf"

  [[ ! -s "${INIT_CNF}" ]] && error "'${INIT_CNF}' was not found or is empty"

  # shellcheck source=product.cnf
  source "${INIT_CNF}"

  [[ -z "${PRODUCT}" ]] && error "PRODUCT must be configured in '${INIT_CNF}'"

  [[ $(grep -c "example-host" ${INIT_CNF}) -eq 1 ]] && error "'${INIT_CNF}' contains default example settings"
  info "Initializing configuration for '${PRODUCT}'"
}

help() {
  echo "

  Usage: $0 action [action action ...]

  Actions include:

	- install
	- version

	- remove
	- purge
	- help

  Default actions are: ${DEFAULT_ACTIONS}
	"
  exit 0
}


main() {
  local ACTIONS

  [[ "$1" == "help" ]] && help  -- Quick cut to clean help output

  initialization

  if [[ $# -gt 0 ]]; then
    ACTIONS="$*"
    info "About to execute custom actions '${ACTIONS}'"
  else
    ACTIONS="${DEFAULT_ACTIONS}"
    info "About to execute default actions '${ACTIONS}'"
  fi

  for ACTION in ${ACTIONS}; do
    if declare -f "${ACTION}" > /dev/null; then
      info "Executing '${ACTION}'..."
      eval "${ACTION}"
    else
      warning "'${ACTION}' not found. Skipping..."
    fi
  done

  completed
}

main "$@"
exit 0
